import raw from "./image-dims.json";

/**
 * Intrinsic pixel size for every image in /public/images.
 *
 * Generated by scripts/image-dims.mjs - run `node scripts/image-dims.mjs`
 * after adding or replacing an image, otherwise the new file falls back to
 * the 4:5 default below.
 *
 * The masonry gallery needs the true ratio before the bitmap loads so each
 * tile can reserve its box (no layout shift) and show the photo uncropped.
 */
const dims = raw as unknown as Record<string, [number, number]>;

const DEFAULT_RATIO: [number, number] = [4, 5];

export function imageSize(src: string): [number, number] {
  return dims[src] ?? DEFAULT_RATIO;
}

export function imageAspectRatio(src: string): string {
  const [w, h] = imageSize(src);
  return `${w} / ${h}`;
}

export const imageCount = Object.keys(dims).length;