export const projects = [
  {
    id: "wardropes",
    title: "Wardropes",
    subtitle: "Bespoke Storage",
    category: "Cabinetry",
    description: "Custom wardrobes designed with precision joinery and refined materiality. Each piece is tailored to the spatial rhythm of the room.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["Mahogany", "Melanin Finish", "Brass Fittings"],
    images: [
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.31.jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.31-(1).jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.31-(2).jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.32.jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.32-(1).jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.33.jpeg",
      "/images/wardropes/WhatsApp-Image-2026-08-29-at-11.33.33-(1).jpeg",
    ],
    featured: true,
  },
  {
    id: "melanin-finish-mahogany",
    title: "Melanin Finish Mahogany",
    subtitle: "Warmth & Depth",
    category: "Finishes",
    description: "A study in tonal richness. Melanin-finished mahogany surfaces that absorb light and return warmth.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["Mahogany", "Melanin Finish"],
    images: [
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.28.jpeg",
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.28-(1).jpeg",
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.29.jpeg",
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.29-(1).jpeg",
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.30.jpeg",
      "/images/melanin-finish-mahogany/WhatsApp-Image-2026-08-29-at-11.33.30-(1).jpeg",
    ],
    featured: true,
  },
  {
    id: "mahogany-solid-wood",
    title: "Solid Mahogany",
    subtitle: "Natural Grain",
    category: "Material",
    description: "Solid mahogany in its truest expression. Honest materiality where the grain tells the story of the tree.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["Solid Mahogany"],
    images: [
      "/images/mahogany-solid-wood/WhatsApp-Image-2026-08-29-at-11.33.24.jpeg",
      "/images/mahogany-solid-wood/WhatsApp-Image-2026-08-29-at-11.33.25.jpeg",
      "/images/mahogany-solid-wood/WhatsApp-Image-2026-08-29-at-11.33.25-(1).jpeg",
      "/images/mahogany-solid-wood/WhatsApp-Image-2026-08-29-at-11.33.26.jpeg",
      "/images/mahogany-solid-wood/WhatsApp-Image-2026-08-29-at-11.33.27.jpeg",
    ],
    featured: true,
  },
  {
    id: "spray-paint-kitchen",
    title: "Spray Paint Kitchen",
    subtitle: "Seamless Surface",
    category: "Kitchen",
    description: "A kitchen where surfaces dissolve into pure color. Spray-painted cabinetry creates a seamless, monolithic presence.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["MDF", "Spray Paint", "Quartz Counter"],
    images: [
      "/images/spray-paint-kitchen/WhatsApp-Image-2026-08-29-at-11.33.22.jpeg",
      "/images/spray-paint-kitchen/WhatsApp-Image-2026-08-29-at-11.33.22-(1).jpeg",
      "/images/spray-paint-kitchen/WhatsApp-Image-2026-08-29-at-11.33.22-(2).jpeg",
      "/images/spray-paint-kitchen/WhatsApp-Image-2026-08-29-at-11.33.23.jpeg",
      "/images/spray-paint-kitchen/WhatsApp-Image-2026-08-29-at-11.33.23-(1).jpeg",
    ],
    featured: true,
  },
  {
    id: "pvc-foilwrap-and-high-gloss-handless-kitchen",
    title: "Foilwrap & High Gloss",
    subtitle: "Refined Minimalism",
    category: "Kitchen",
    description: "PVC foilwrap meets high-gloss cabinetry in a handleless composition. Clean lines and tactile surfaces.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["PVC Foilwrap", "High Gloss", "Handleless"],
    images: [
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.16-(1).jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.17.jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.17.jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.17-(1).jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.17-(2).jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.17-(3).jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.18.jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.18-(1).jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.21.jpeg",
      "/images/pvc-foilwrap-and-high-gloss-handless-kitchen/WhatsApp-Image-2026-08-29-at-11.33.21-(1).jpeg",
    ],
    featured: true,
  },
  {
    id: "handless-melanin",
    title: "Handless Melanin",
    subtitle: "Integrated Form",
    category: "Cabinetry",
    description: "Handleless melanin-finished cabinetry where form follows function. An exercise in restraint and material confidence.",
    year: "2024",
    location: "Nairobi, Kenya",
    materials: ["Melanin Board", "Integrated Handles"],
    images: [
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.09.jpeg",
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.11.jpeg",
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.12.jpeg",
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.13.jpeg",
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.13-(1).jpeg",
      "/images/handless-melanin/WhatsApp-Image-2026-08-29-at-11.33.16.jpeg",
    ],
    featured: true,
  },
];

export const projectById = (id: string) =>
  projects.find((p) => p.id === id);
